spring:
  application:
    name: Flight_reservation
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/flight_reservation_db
    username: root
    password: nvq211241738

app:
  payment:
    vnPay:
      url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
      tmnCode: BVE8BMH9
      secretKey: PYXFIG8OJXNULBF39N470EZ1684K306T
      returnUrl: http://localhost:8080/api/payments/vn-pay-callback
      version: 2.1.0
      command: pay
      orderType: other
