spring:
  application:
    name: Flight_reservation
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

app:
  payment:
    vnPay:
      url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
      tmnCode: ${VNPAY_TMNCODE}
      secretKey: ${VNPAY_KEY}
      returnUrl: http://localhost:8080/api/payments/vn-pay-callback
      version: 2.1.0
      command: pay
      orderType: other

jwt:
  secret: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"